#!/bin/bash
npm install express --save
npm install http --save
npm install fs --save
npm install path --save
npm install body-parser --save
npm install cors --save
npm install events --save
npm install ip --save
npm install node-schedule --save
npm install process --save
npm install ps-node --save
npm install shelljs --save
npm install redis --save
npm install redis-manager-utils --save
npm install tweetnacl --save
npm install tweetnacl-sealedbox-js --save
npm install tweetnacl-util --save
npm install util --save
npm install ws --save